In [24]:
#import library yang di butuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

In [25]:
#create classfier
lr = LogisticRegression(solver='lbfgs')
svc = LinearSVC(C = 1.0)
rfc = RandomForestClassifier(n_estimators = 100)

In [26]:
hotel = pd.read_csv('hotel_bookings.csv')
hotel

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.00,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.00,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.50,0,0,Canceled,2015-04-22
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0,0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0,0,Check-Out,2015-07-05
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0,1,Check-Out,2015-07-05
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,94.71,0,0,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0,3,Check-Out,2015-07-05
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,8.0,NaN,0,Contract,97.50,0,0,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0,0,Check-Out,2015-07-02
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0,1,Check-Out,2015-07-05
20,Resort Hotel,0,37,2015,July,27,1,1,4,1,...,No Deposit,241.0,NaN,0,Transient,97.29,0,1,Check-Out,2015-07-06
21,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,84.67,0,1,Check-Out,2015-07-07
23,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,NaN,0,Transient,99.67,0,1,Check-Out,2015-07-07
24,Resort Hotel,0,127,2015,July,27,1,2,5,2,...,No Deposit,115.0,NaN,0,Contract,94.95,0,1,Check-Out,2015-07-01
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,No Deposit,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08
26,Resort Hotel,0,48,2015,July,27,1,2,5,2,...,No Deposit,8.0,NaN,0,Contract,79.50,0,0,Check-Out,2015-07-08
27,Resort Hotel,1,60,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,107.00,0,2,Canceled,2015-05-11
28,Resort Hotel,0,77,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,94.00,0,0,Check-Out,2015-07-08
29,Resort Hotel,0,99,2015,July,27,1,2,5,2,...,No Deposit,240.0,NaN,0,Transient,87.30,1,1,Check-Out,2015-07-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119360,City Hotel,0,195,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,1,Check-Out,2017-09-04
119361,City Hotel,0,100,2017,August,35,31,1,3,2,...,No Deposit,16.0,NaN,0,Transient,95.85,0,0,Check-Out,2017-09-04
119362,City Hotel,0,198,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,119.17,0,2,Check-Out,2017-09-04
119363,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,1,Check-Out,2017-09-04
119364,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,92.17,0,2,Check-Out,2017-09-04
119365,City Hotel,0,54,2017,August,35,27,3,5,1,...,No Deposit,14.0,NaN,0,Transient,266.75,0,1,Check-Out,2017-09-04
119366,City Hotel,0,210,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,1,Check-Out,2017-09-04
119367,City Hotel,0,212,2017,August,35,28,2,5,2,...,No Deposit,7.0,NaN,0,Transient,85.59,0,0,Check-Out,2017-09-04
119368,City Hotel,0,261,2017,August,35,30,1,4,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-04
119369,City Hotel,0,207,2017,August,34,25,3,7,2,...,No Deposit,14.0,NaN,0,Transient,96.25,0,2,Check-Out,2017-09-04
119370,City Hotel,0,201,2017,August,35,30,1,4,1,...,No Deposit,9.0,NaN,0,Transient,108.00,0,2,Check-Out,2017-09-04
119371,City Hotel,0,175,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,2,Check-Out,2017-09-04
119372,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119373,City Hotel,0,175,2017,August,35,31,1,3,1,...,No Deposit,42.0,NaN,0,Transient,82.35,0,1,Check-Out,2017-09-04
119374,City Hotel,0,201,2017,August,35,29,1,5,2,...,No Deposit,9.0,NaN,0,Transient,117.00,0,2,Check-Out,2017-09-04
119375,City Hotel,0,200,2017,August,35,30,1,4,2,...,No Deposit,16.0,NaN,0,Transient,85.50,0,1,Check-Out,2017-09-04
119376,City Hotel,0,165,2017,August,35,29,1,5,3,...,No Deposit,9.0,NaN,0,Transient,209.25,0,3,Check-Out,2017-09-04
119377,City Hotel,0,185,2017,August,35,30,1,4,2,...,No Deposit,9.0,NaN,0,Transient,99.00,0,1,Check-Out,2017-09-04
119378,City Hotel,0,247,2017,August,35,31,1,3,2,...,No Deposit,42.0,NaN,0,Transient,86.85,0,0,Check-Out,2017-09-04
119379,City Hotel,0,109,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,155.00,0,1,Check-Out,2017-09-04
119380,City Hotel,0,44,2017,August,35,31,1,3,2,...,No Deposit,9.0,NaN,0,Transient,140.75,0,1,Check-Out,2017-09-04
119381,City Hotel,0,188,2017,August,35,31,2,3,2,...,No Deposit,14.0,NaN,0,Transient,99.00,0,0,Check-Out,2017-09-05
119382,City Hotel,0,135,2017,August,35,30,2,4,3,...,No Deposit,7.0,NaN,0,Transient,209.00,0,0,Check-Out,2017-09-05
119383,City Hotel,0,164,2017,August,35,31,2,4,2,...,No Deposit,42.0,NaN,0,Transient,87.60,0,0,Check-Out,2017-09-06
119384,City Hotel,0,21,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,2,Check-Out,2017-09-06
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [27]:
hotel['hotel'].value_counts().head(5)

City Hotel      79330
Resort Hotel    40060
Name: hotel, dtype: int64

In [28]:
hotel['deposit_type'].value_counts()

No Deposit    104641
Non Refund     14587
Refundable       162
Name: deposit_type, dtype: int64

In [29]:
hotel['arrival_date_month'].value_counts()

August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: arrival_date_month, dtype: int64

In [50]:
hotel['company'].value_counts().head(5)

0.0      112593
40.0        927
223.0       784
67.0        267
45.0        250
Name: company, dtype: int64

In [56]:
hotel['reservation_status'].value_counts().head(5)

Check-Out    75166
Canceled     43017
No-Show       1207
Name: reservation_status, dtype: int64

In [ ]:
hotel['customer_type'].value_counts().head(5)

In [30]:
hotel.loc[hotel['hotel'] == 'Resort Hotel','hotel']= 1
hotel.loc[hotel['hotel'] == 'City Hotel' ,'hotel']= 2

In [31]:
hotel.loc[hotel['deposit_type'] == 'No Deposit','deposit_type']= 1
hotel.loc[hotel['deposit_type'] == 'Non Refund' ,'deposit_type']= 2
hotel.loc[hotel['deposit_type'] == 'Refundable' ,'deposit_type']= 3

In [33]:
hotel.loc[hotel['arrival_date_month'] == 'January','arrival_date_month']= 1
hotel.loc[hotel['arrival_date_month'] == 'February','arrival_date_month']= 2
hotel.loc[hotel['arrival_date_month'] == 'March','arrival_date_month']= 3
hotel.loc[hotel['arrival_date_month'] == 'April','arrival_date_month']= 4
hotel.loc[hotel['arrival_date_month'] == 'May','arrival_date_month']= 5
hotel.loc[hotel['arrival_date_month'] == 'June','arrival_date_month']= 6
hotel.loc[hotel['arrival_date_month'] == 'July','arrival_date_month']= 7
hotel.loc[hotel['arrival_date_month'] == 'August','arrival_date_month']= 8
hotel.loc[hotel['arrival_date_month'] == 'September','arrival_date_month']= 9
hotel.loc[hotel['arrival_date_month'] == 'October','arrival_date_month']= 10
hotel.loc[hotel['arrival_date_month'] == 'November','arrival_date_month']= 11
hotel.loc[hotel['arrival_date_month'] == 'December','arrival_date_month']= 12

In [54]:
hotel.loc[hotel['customer_type'] == 'Transient','customer_type']= 1
hotel.loc[hotel['customer_type'] == 'Transient-Party' ,'customer_type']= 2
hotel.loc[hotel['customer_type'] == 'Contract' ,'customer_type']= 3
hotel.loc[hotel['customer_type'] == 'Group' ,'customer_type']= 4

In [60]:
hotel.loc[hotel['reservation_status'] == 'Check-Out','reservation_status']= 1
hotel.loc[hotel['reservation_status'] == 'Canceled' ,'reservation_status']= 2
hotel.loc[hotel['reservation_status'] == 'No-Show' ,'reservation_status']= 3

In [62]:
hotel = hotel.drop(['reservation_status_date'], axis = 1)

In [59]:
hotel['agent'] = hotel['agent'].replace(np.nan, 0)
hotel['company'] = hotel['company'].replace(np.nan, 0)

In [63]:
hotel

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,0,0,342,2015,7,27,1,0,0,2,...,3,1,0.0,0.0,0,1,0.00,0,0,1
1,0,0,737,2015,7,27,1,0,0,2,...,4,1,0.0,0.0,0,1,0.00,0,0,1
2,0,0,7,2015,7,27,1,0,1,1,...,0,1,0.0,0.0,0,1,75.00,0,0,1
3,0,0,13,2015,7,27,1,0,1,1,...,0,1,304.0,0.0,0,1,75.00,0,0,1
4,0,0,14,2015,7,27,1,0,2,2,...,0,1,240.0,0.0,0,1,98.00,0,1,1
5,0,0,14,2015,7,27,1,0,2,2,...,0,1,240.0,0.0,0,1,98.00,0,1,1
6,0,0,0,2015,7,27,1,0,2,2,...,0,1,0.0,0.0,0,1,107.00,0,0,1
7,0,0,9,2015,7,27,1,0,2,2,...,0,1,303.0,0.0,0,1,103.00,0,1,1
8,0,1,85,2015,7,27,1,0,3,2,...,0,1,240.0,0.0,0,1,82.00,0,1,2
9,0,1,75,2015,7,27,1,0,3,2,...,0,1,15.0,0.0,0,1,105.50,0,0,2
10,0,1,23,2015,7,27,1,0,4,2,...,0,1,240.0,0.0,0,1,123.00,0,0,2
11,0,0,35,2015,7,27,1,0,4,2,...,0,1,240.0,0.0,0,1,145.00,0,0,1
12,0,0,68,2015,7,27,1,0,4,2,...,0,1,240.0,0.0,0,1,97.00,0,3,1
13,0,0,18,2015,7,27,1,0,4,2,...,1,1,241.0,0.0,0,1,154.77,0,1,1
14,0,0,37,2015,7,27,1,0,4,2,...,0,1,241.0,0.0,0,1,94.71,0,0,1
15,0,0,68,2015,7,27,1,0,4,2,...,0,1,240.0,0.0,0,1,97.00,0,3,1
16,0,0,37,2015,7,27,1,0,4,2,...,0,3,8.0,0.0,0,3,97.50,0,0,1
17,0,0,12,2015,7,27,1,0,1,2,...,0,1,240.0,0.0,0,1,88.20,0,0,1
18,0,0,0,2015,7,27,1,0,1,2,...,0,1,0.0,110.0,0,1,107.42,0,0,1
19,0,0,7,2015,7,27,1,0,4,2,...,0,1,250.0,0.0,0,1,153.00,0,1,1
20,0,0,37,2015,7,27,1,1,4,1,...,0,1,241.0,0.0,0,1,97.29,0,1,1
21,0,0,72,2015,7,27,1,2,4,2,...,1,1,250.0,0.0,0,1,84.67,0,1,1
22,0,0,72,2015,7,27,1,2,4,2,...,1,1,250.0,0.0,0,1,84.67,0,1,1
23,0,0,72,2015,7,27,1,2,4,2,...,1,1,250.0,0.0,0,1,99.67,0,1,1
24,0,0,127,2015,7,27,1,2,5,2,...,0,3,115.0,0.0,0,3,94.95,0,1,1
25,0,0,78,2015,7,27,1,2,5,2,...,0,1,5.0,0.0,0,1,63.60,1,0,1
26,0,0,48,2015,7,27,1,2,5,2,...,0,3,8.0,0.0,0,3,79.50,0,0,1
27,0,1,60,2015,7,27,1,2,5,2,...,0,1,240.0,0.0,0,1,107.00,0,2,2
28,0,0,77,2015,7,27,1,2,5,2,...,0,1,240.0,0.0,0,1,94.00,0,0,1
29,0,0,99,2015,7,27,1,2,5,2,...,0,1,240.0,0.0,0,1,87.30,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119360,1,0,195,2017,8,35,29,1,5,2,...,0,1,9.0,0.0,0,1,117.00,0,1,1
119361,1,0,100,2017,8,35,31,1,3,2,...,0,1,16.0,0.0,0,1,95.85,0,0,1
119362,1,0,198,2017,8,35,29,1,5,2,...,2,1,9.0,0.0,0,1,119.17,0,2,1
119363,1,0,212,2017,8,35,28,2,5,2,...,0,1,7.0,0.0,0,1,92.17,0,1,1
119364,1,0,212,2017,8,35,28,2,5,2,...,0,1,7.0,0.0,0,1,92.17,0,2,1
119365,1,0,54,2017,8,35,27,3,5,1,...,0,1,14.0,0.0,0,1,266.75,0,1,1
119366,1,0,210,2017,8,35,28,2,5,2,...,0,1,7.0,0.0,0,1,85.59,0,1,1
119367,1,0,212,2017,8,35,28,2,5,2,...,0,1,7.0,0.0,0,1,85.59,0,0,1
119368,1,0,261,2017,8,35,30,1,4,2,...,0,1,14.0,0.0,0,1,99.00,0,0,1
119369,1,0,207,2017,8,34,25,3,7,2,...,0,1,14.0,0.0,0,1,96.25,0,2,1
119370,1,0,201,2017,8,35,30,1,4,1,...,0,1,9.0,0.0,0,1,108.00,0,2,1
119371,1,0,175,2017,8,35,31,1,3,2,...,1,1,42.0,0.0,0,1,86.85,0,2,1
119372,1,0,175,2017,8,35,31,1,3,1,...,0,1,42.0,0.0,0,1,82.35,0,1,1
119373,1,0,175,2017,8,35,31,1,3,1,...,0,1,42.0,0.0,0,1,82.35,0,1,1
119374,1,0,201,2017,8,35,29,1,5,2,...,0,1,9.0,0.0,0,1,117.00,0,2,1
119375,1,0,200,2017,8,35,30,1,4,2,...,0,1,16.0,0.0,0,1,85.50,0,1,1
119376,1,0,165,2017,8,35,29,1,5,3,...,0,1,9.0,0.0,0,1,209.25,0,3,1
119377,1,0,185,2017,8,35,30,1,4,2,...,0,1,9.0,0.0,0,1,99.00,0,1,1
119378,1,0,247,2017,8,35,31,1,3,2,...,0,1,42.0,0.0,0,1,86.85,0,0,1
119379,1,0,109,2017,8,35,31,1,3,2,...,0,1,9.0,0.0,0,1,155.00,0,1,1
119380,1,0,44,2017,8,35,31,1,3,2,...,0,1,9.0,0.0,0,1,140.75,0,1,1
119381,1,0,188,2017,8,35,31,2,3,2,...,0,1,14.0,0.0,0,1,99.00,0,0,1
119382,1,0,135,2017,8,35,30,2,4,3,...,0,1,7.0,0.0,0,1,209.00,0,0,1
119383,1,0,164,2017,8,35,31,2,4,2,...,0,1,42.0,0.0,0,1,87.60,0,0,1
119384,1,0,21,2017,8,35,30,2,5,2,...,0,1,394.0,0.0,0,1,96.14,0,2,1
119385,1,0,23,2017,8,35,30,2,5,2,...,0,1,394.0,0.0,0,1,96.14,0,0,1
119386,1,0,102,2017,8,35,31,2,5,3,...,0,1,9.0,0.0,0,1,225.43,0,2,1
119387,1,0,34,2017,8,35,31,2,5,2,...,0,1,9.0,0.0,0,1,157.71,0,4,1
119388,1,0,109,2017,8,35,31,2,5,2,...,0,1,89.0,0.0,0,1,104.40,0,0,1
119389,1,0,205,2017,8,35,29,2,7,2,...,0,1,9.0,0.0,0,1,151.20,0,2,1